// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: songApi.proto

package go_micro_api_songApi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SongApi service

func NewSongApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SongApi service

type SongApiService interface {
	Search(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetSongUrl(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type songApiService struct {
	c    client.Client
	name string
}

func NewSongApiService(name string, c client.Client) SongApiService {
	return &songApiService{
		c:    c,
		name: name,
	}
}

func (c *songApiService) Search(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SongApi.Search", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songApiService) GetSongUrl(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SongApi.GetSongUrl", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SongApi service

type SongApiHandler interface {
	Search(context.Context, *Request, *Response) error
	GetSongUrl(context.Context, *Request, *Response) error
}

func RegisterSongApiHandler(s server.Server, hdlr SongApiHandler, opts ...server.HandlerOption) error {
	type songApi interface {
		Search(ctx context.Context, in *Request, out *Response) error
		GetSongUrl(ctx context.Context, in *Request, out *Response) error
	}
	type SongApi struct {
		songApi
	}
	h := &songApiHandler{hdlr}
	return s.Handle(s.NewHandler(&SongApi{h}, opts...))
}

type songApiHandler struct {
	SongApiHandler
}

func (h *songApiHandler) Search(ctx context.Context, in *Request, out *Response) error {
	return h.SongApiHandler.Search(ctx, in, out)
}

func (h *songApiHandler) GetSongUrl(ctx context.Context, in *Request, out *Response) error {
	return h.SongApiHandler.GetSongUrl(ctx, in, out)
}
